name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: get_avr-gcc
      run: sudo apt-get install gcc-avr binutils-avr avr-libc
#     - name: configure
#       run: ./3_Implementation/Build/servo_res.elf
    - name: make
      run: make -C 3_Implementation
#     - name: make check
#       run: make check
#     - name: make distcheck
#       run: make distcheck
