name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: get_avr-gcc
      run: sudo apt-get install gcc-avr binutils-avr avr-libc
    
#     - name: configure
#       run: ./configure
      
    - name: Install dependencies
      run: make
      
    - name: Run check
      run: make check
      
    - name: Run distcheck
      run: make distcheck
